## Creating a Numpy array




In [1]:
#Importing numpy

import numpy as np

In [5]:
# We can create a numpy array using a function called np.array

a = np.array([1,2,3])
print(a) # This is a 1d array

# How do we know it's a numpy array, we can know it's a numpy array by finding it's type

print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#2d
# we can also call this a matrix

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3d
c = np.array([[[1,2],[2,3],[4,5],[6,7]]])
print(c)

[[[1 2]
  [2 3]
  [4 5]
  [6 7]]]
