## Creating a Numpy array




In [2]:
#Importing numpy

import numpy as np

In [3]:
# We can create a numpy array using a function called np.array

a = np.array([1,2,3])
print(a) # This is a 1d array

# How do we know it's a numpy array, we can know it's a numpy array by finding it's type

print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
#2d
# we can also call this a matrix

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
# 3d
c = np.array([[[1,2],[2,3],[4,5],[6,7]]])
print(c)

[[[1 2]
  [2 3]
  [4 5]
  [6 7]]]


In [6]:
# dtype
# By default the data types of array are integers
# We can also create a array of float

np.array([1,2,3],dtype=float)



array([1., 2., 3.])

In [7]:
#Creating our own array using bool datatype
# Now we will get the output as true beacause any non zero value is considered as true by python

np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [8]:
# We can also make an array of complex data type
#Although we won't use complex for the maximum times we will use float

np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
# np.arange -> Let's say we want a range of numbers in an array so we can 
# do this by using np. range , we can specify a range here 
# we follow index slicing here

range1 = np.arange(1,11)
print(range1)

#with strides so we can get alternate numbers

range2 = np.arange(1,11,2)
print(range2)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


np.arange 

start: The starting value of the sequence.
stop: The end value of the sequence (exclusive).
step: The difference between each pair of consecutive values.
dtype: The desired data-type for the array (optional).

here we have start stop and increase value by two

In [10]:
# with reshape , if we want to convert this into 5 x 2

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
# the product of two numbers should be equal to the numbers that are inside the array

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
#np.ones and np.zeros

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
#np.zeros -> This is used to create an array full of zeros

# Create a 1-D array of zeros with length 5
array_1d = np.zeros(5)
print(array_1d)  # Output: [0. 0. 0. 0. 0.]

# Create a 2-D array of zeros with 2 rows and 3 columns
array_2d = np.zeros((2, 3))
print(array_2d)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]

# Create a 3-D array of zeros with shape (2, 2, 2)
array_3d = np.zeros((2, 2, 2))
print(array_3d)
# Output:
# [[[0. 0.]
#   [0. 0.]]
#
#  [[0. 0.]
#   [0. 0.]]]


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


np.ones and np.zeros are indeed helpful when creating neural networks. They are often used for initializing the weights and biases of the neural network layers. Proper initialization is crucial for the training process of neural networks, as it can significantly affect the convergence speed and overall performance.

So whenever we want to initialize values quickly we should use this

In [16]:
#np.ones -> This is used to create an array full of ones

# Create a 1-D array of ones with length 5
array_1d = np.ones(5)
print(array_1d)  # Output: [1. 1. 1. 1. 1.]

# Create a 2-D array of ones with 2 rows and 3 columns
array_2d = np.ones((2, 3))
print(array_2d)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]]

# Create a 3-D array of ones with shape (2, 2, 2)
array_3d = np.ones((2, 2, 2))
print(array_3d)
# Output:
# [[[1. 1.]
#   [1. 1.]]
#
#  [[1. 1.]
#   [1. 1.]]]

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


np.random is a submodule of NumPy used for generating random numbers and performing random sampling. It provides a wide range of functions to create arrays of random numbers from various distributions, which is useful for simulations, statistical analysis, and other applications that require randomness.

In case we want to initialize random values

In [14]:
#np.random

np.random.random((3,4))

array([[0.20299485, 0.85906174, 0.24800926, 0.15744175],
       [0.39672091, 0.79461995, 0.96288999, 0.67287128],
       [0.79530997, 0.74658763, 0.19863769, 0.54152151]])

In [17]:
#np.linspace -> This has three parameters lower range , upper range and number of items
# This is important

np.linspace(-10,10,10) #we got the default value as float beacuse float is more useful

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

What does linspace do ?
-> So this generates points on equal distance in a given range

In [18]:
#np.identity -> we can create an identity matrix
# basically the diagonal items are one and the rest of the items are zeros

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
array1 = np.array([[1,2],[2,3]])
array_3d = np.array([[[1, 2], [3, 4], [5, 6]], 
                     [[7, 8], [9, 10], [11, 12]]])

print(array_3d.shape)

# 2d arrays stacked on top of each other are 3d arrays

(2, 3, 2)


In [36]:
np.array([[[1,2],[2,3],[3,4]],
         [[2,3],[3,4],[4,5]]])

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

Numpy arrays are by default float