## Creating a Numpy array




In [32]:
#Importing numpy

import numpy as np

In [33]:
# We can create a numpy array using a function called np.array

a = np.array([1,2,3])
print(a) # This is a 1d array

# How do we know it's a numpy array, we can know it's a numpy array by finding it's type

print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [34]:
#2d
# we can also call this a matrix

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [35]:
# 3d
c = np.array([[[1,2],[2,3],[4,5],[6,7]]])
print(c)

[[[1 2]
  [2 3]
  [4 5]
  [6 7]]]


In [36]:
# dtype
# By default the data types of array are integers
# We can also create a array of float

np.array([1,2,3],dtype=float)



array([1., 2., 3.])

In [37]:
#Creating our own array using bool datatype
# Now we will get the output as true beacause any non zero value is considered as true by python

np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [38]:
# We can also make an array of complex data type
#Although we won't use complex for the maximum times we will use float

np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [39]:
# np.arange -> Let's say we want a range of numbers in an array so we can 
# do this by using np. range , we can specify a range here 
# we follow index slicing here

range1 = np.arange(1,11)
print(range1)

#with strides so we can get alternate numbers

range2 = np.arange(1,11,2)
print(range2)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [41]:
# with reshape , if we want to convert this into 5 x 2

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
# the product of two numbers should be equal to the numbers that are inside the array

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
np.arange(1,26).reshape(5,5)

ValueError: cannot reshape array of size 13 into shape (5,5)